import { Category } from "@/constants/Categories"

/**
 * Hand-curated keyword -> category table, German + English. Checked first
 * by categorizeIngredient, before the generated fallback table. Longest
 * matching keyword wins at lookup time (see utils/categorize.ts).
 */
export const CURATED_CATEGORY_KEYWORDS: [string, Category][] = [
  // Fruit & Vegetables
  ["apfel", Category.FRUIT_VEGETABLES],
  ["äpfel", Category.FRUIT_VEGETABLES],
  ["banane", Category.FRUIT_VEGETABLES],
  ["birne", Category.FRUIT_VEGETABLES],
  ["weintraube", Category.FRUIT_VEGETABLES],
  ["traube", Category.FRUIT_VEGETABLES],
  ["beere", Category.FRUIT_VEGETABLES],
  ["erdbeer", Category.FRUIT_VEGETABLES],
  ["himbeer", Category.FRUIT_VEGETABLES],
  ["heidelbeer", Category.FRUIT_VEGETABLES],
  ["blaubeer", Category.FRUIT_VEGETABLES],
  ["zitrone", Category.FRUIT_VEGETABLES],
  ["orange", Category.FRUIT_VEGETABLES],
  ["mandarine", Category.FRUIT_VEGETABLES],
  ["kiwi", Category.FRUIT_VEGETABLES],
  ["mango", Category.FRUIT_VEGETABLES],
  ["avocado", Category.FRUIT_VEGETABLES],
  ["melone", Category.FRUIT_VEGETABLES],
  ["pfirsich", Category.FRUIT_VEGETABLES],
  ["pflaume", Category.FRUIT_VEGETABLES],
  ["kirsch", Category.FRUIT_VEGETABLES],
  ["ananas", Category.FRUIT_VEGETABLES],
  ["tomate", Category.FRUIT_VEGETABLES],
  ["gurke", Category.FRUIT_VEGETABLES],
  ["paprika", Category.FRUIT_VEGETABLES],
  ["salat", Category.FRUIT_VEGETABLES],
  ["karotte", Category.FRUIT_VEGETABLES],
  ["möhre", Category.FRUIT_VEGETABLES],
  ["zwiebel", Category.FRUIT_VEGETABLES],
  ["knoblauch", Category.FRUIT_VEGETABLES],
  ["kartoffel", Category.FRUIT_VEGETABLES],
  ["brokkoli", Category.FRUIT_VEGETABLES],
  ["blumenkohl", Category.FRUIT_VEGETABLES],
  ["kohl", Category.FRUIT_VEGETABLES],
  ["spinat", Category.FRUIT_VEGETABLES],
  ["zucchini", Category.FRUIT_VEGETABLES],
  ["aubergine", Category.FRUIT_VEGETABLES],
  ["lauch", Category.FRUIT_VEGETABLES],
  ["sellerie", Category.FRUIT_VEGETABLES],
  ["radies", Category.FRUIT_VEGETABLES],
  ["pilz", Category.FRUIT_VEGETABLES],
  ["champignon", Category.FRUIT_VEGETABLES],
  ["kräuter", Category.FRUIT_VEGETABLES],
  ["petersilie", Category.FRUIT_VEGETABLES],
  ["basilikum", Category.FRUIT_VEGETABLES],
  ["ingwer", Category.FRUIT_VEGETABLES],
  ["kürbis", Category.FRUIT_VEGETABLES],
  ["rucola", Category.FRUIT_VEGETABLES],
  ["feldsalat", Category.FRUIT_VEGETABLES],
  ["apple", Category.FRUIT_VEGETABLES],
  ["banana", Category.FRUIT_VEGETABLES],
  ["grape", Category.FRUIT_VEGETABLES],
  ["tomato", Category.FRUIT_VEGETABLES],
  ["cucumber", Category.FRUIT_VEGETABLES],
  ["carrot", Category.FRUIT_VEGETABLES],
  ["onion", Category.FRUIT_VEGETABLES],
  ["potato", Category.FRUIT_VEGETABLES],
  ["lettuce", Category.FRUIT_VEGETABLES],
  ["broccoli", Category.FRUIT_VEGETABLES],
  ["mushroom", Category.FRUIT_VEGETABLES],
  ["lemon", Category.FRUIT_VEGETABLES],

  // Dairy & Cheese
  ["vollmilch", Category.DAIRY_CHEESE],
  ["milch", Category.DAIRY_CHEESE],
  ["butter", Category.DAIRY_CHEESE],
  ["käse", Category.DAIRY_CHEESE],
  ["quark", Category.DAIRY_CHEESE],
  ["sahne", Category.DAIRY_CHEESE],
  ["joghurt", Category.DAIRY_CHEESE],
  ["jogurt", Category.DAIRY_CHEESE],
  ["eier", Category.DAIRY_CHEESE],
  ["frischkäse", Category.DAIRY_CHEESE],
  ["gouda", Category.DAIRY_CHEESE],
  ["edamer", Category.DAIRY_CHEESE],
  ["mozzarella", Category.DAIRY_CHEESE],
  ["parmesan", Category.DAIRY_CHEESE],
  ["feta", Category.DAIRY_CHEESE],
  ["camembert", Category.DAIRY_CHEESE],
  ["brie", Category.DAIRY_CHEESE],
  ["schmand", Category.DAIRY_CHEESE],
  ["margarine", Category.DAIRY_CHEESE],
  ["buttermilch", Category.DAIRY_CHEESE],
  ["kefir", Category.DAIRY_CHEESE],
  ["pudding", Category.DAIRY_CHEESE],
  ["milk", Category.DAIRY_CHEESE],
  ["cheese", Category.DAIRY_CHEESE],
  ["yogurt", Category.DAIRY_CHEESE],
  ["yoghurt", Category.DAIRY_CHEESE],
  ["cream", Category.DAIRY_CHEESE],
  ["eggs", Category.DAIRY_CHEESE],

  // Meat & Fish
  ["rindfleisch", Category.MEAT_FISH],
  ["wurst", Category.MEAT_FISH],
  ["schinken", Category.MEAT_FISH],
  ["salami", Category.MEAT_FISH],
  ["speck", Category.MEAT_FISH],
  ["hähnchen", Category.MEAT_FISH],
  ["hühn", Category.MEAT_FISH],
  ["huhn", Category.MEAT_FISH],
  ["pute", Category.MEAT_FISH],
  ["rind", Category.MEAT_FISH],
  ["schwein", Category.MEAT_FISH],
  ["lamm", Category.MEAT_FISH],
  ["steak", Category.MEAT_FISH],
  ["schnitzel", Category.MEAT_FISH],
  ["hackfleisch", Category.MEAT_FISH],
  ["hack", Category.MEAT_FISH],
  ["gulasch", Category.MEAT_FISH],
  ["bratwurst", Category.MEAT_FISH],
  ["leberwurst", Category.MEAT_FISH],
  ["fisch", Category.MEAT_FISH],
  ["lachs", Category.MEAT_FISH],
  ["thunfisch", Category.MEAT_FISH],
  ["forelle", Category.MEAT_FISH],
  ["garnele", Category.MEAT_FISH],
  ["shrimp", Category.MEAT_FISH],
  ["kabeljau", Category.MEAT_FISH],
  ["hering", Category.MEAT_FISH],
  ["fischstäbchen", Category.FROZEN],
  ["meat", Category.MEAT_FISH],
  ["chicken", Category.MEAT_FISH],
  ["chicken breast", Category.MEAT_FISH],
  ["beef", Category.MEAT_FISH],
  ["pork", Category.MEAT_FISH],
  ["sausage", Category.MEAT_FISH],
  ["ham", Category.MEAT_FISH],
  ["salmon", Category.MEAT_FISH],
  ["tuna", Category.MEAT_FISH],

  // Bread & Bakery
  ["brot", Category.BREAD_BAKERY],
  ["brötchen", Category.BREAD_BAKERY],
  ["semmel", Category.BREAD_BAKERY],
  ["toast", Category.BREAD_BAKERY],
  ["baguette", Category.BREAD_BAKERY],
  ["croissant", Category.BREAD_BAKERY],
  ["brezel", Category.BREAD_BAKERY],
  ["laugenstange", Category.BREAD_BAKERY],
  ["laugen", Category.BREAD_BAKERY],
  ["kuchen", Category.BREAD_BAKERY],
  ["torte", Category.BREAD_BAKERY],
  ["muffin", Category.BREAD_BAKERY],
  ["donut", Category.BREAD_BAKERY],
  ["zwieback", Category.BREAD_BAKERY],
  ["knäcke", Category.BREAD_BAKERY],
  ["bread", Category.BREAD_BAKERY],
  ["bun", Category.BREAD_BAKERY],
  ["bagel", Category.BREAD_BAKERY],
  ["cake", Category.BREAD_BAKERY],

  // Drinks
  ["wasser", Category.DRINKS],
  ["mineralwasser", Category.DRINKS],
  ["saft", Category.DRINKS],
  ["apfelsaft", Category.DRINKS],
  ["apfelschorle", Category.DRINKS],
  ["schorle", Category.DRINKS],
  ["kaffee", Category.DRINKS],
  ["cola", Category.DRINKS],
  ["wein", Category.DRINKS],
  ["rotwein", Category.DRINKS],
  ["weißwein", Category.DRINKS],
  ["sekt", Category.DRINKS],
  ["schnaps", Category.DRINKS],
  ["bier", Category.DRINKS],
  ["tee", Category.DRINKS],
  ["kakao", Category.DRINKS],
  ["smoothie", Category.DRINKS],
  ["sprudel", Category.DRINKS],
  ["limonade", Category.DRINKS],
  ["limo", Category.DRINKS],
  ["water", Category.DRINKS],
  ["juice", Category.DRINKS],
  ["coffee", Category.DRINKS],
  ["wine", Category.DRINKS],
  ["beer", Category.DRINKS],
  ["tea", Category.DRINKS],

  // Sweets & Snacks
  ["schokolade", Category.SWEETS_SNACKS],
  ["schoko", Category.SWEETS_SNACKS],
  ["bonbon", Category.SWEETS_SNACKS],
  ["keks", Category.SWEETS_SNACKS],
  ["kekse", Category.SWEETS_SNACKS],
  ["gummibär", Category.SWEETS_SNACKS],
  ["haribo", Category.SWEETS_SNACKS],
  ["riegel", Category.SWEETS_SNACKS],
  ["chips", Category.SWEETS_SNACKS],
  ["salzstange", Category.SWEETS_SNACKS],
  ["erdnuss", Category.SWEETS_SNACKS],
  ["nüsse", Category.SWEETS_SNACKS],
  ["popcorn", Category.SWEETS_SNACKS],
  ["cracker", Category.SWEETS_SNACKS],
  ["waffel", Category.SWEETS_SNACKS],
  ["praline", Category.SWEETS_SNACKS],
  ["lakritz", Category.SWEETS_SNACKS],
  ["kaugummi", Category.SWEETS_SNACKS],
  ["chocolate", Category.SWEETS_SNACKS],
  ["candy", Category.SWEETS_SNACKS],
  ["cookie", Category.SWEETS_SNACKS],
  ["snack", Category.SWEETS_SNACKS],

  // Frozen
  ["tiefkühlpizza", Category.FROZEN],
  ["tiefkühlgemüse", Category.FROZEN],
  ["tiefkühl", Category.FROZEN],
  ["tk-", Category.FROZEN],
  ["pommes", Category.FROZEN],
  ["eiscreme", Category.FROZEN],
  ["speiseeis", Category.FROZEN],
  ["frozen", Category.FROZEN],
  ["ice cream", Category.FROZEN],

  // Pantry
  ["spaghetti", Category.PANTRY],
  ["nudeln", Category.PANTRY],
  ["mehl", Category.PANTRY],
  ["zucker", Category.PANTRY],
  ["salz", Category.PANTRY],
  ["öl", Category.PANTRY],
  ["sonnenblumenöl", Category.PANTRY],
  ["olivenöl", Category.PANTRY],
  ["konserve", Category.PANTRY],
  ["essig", Category.PANTRY],
  ["reis", Category.PANTRY],
  ["müsli", Category.PANTRY],
  ["marmelade", Category.PANTRY],
  ["honig", Category.PANTRY],
  ["nutella", Category.PANTRY],
  ["ketchup", Category.PANTRY],
  ["senf", Category.PANTRY],
  ["mayo", Category.PANTRY],
  ["mayonnaise", Category.PANTRY],
  ["soße", Category.PANTRY],
  ["sauce", Category.PANTRY],
  ["brühe", Category.PANTRY],
  ["suppe", Category.PANTRY],
  ["backpulver", Category.PANTRY],
  ["hefe", Category.PANTRY],
  ["cornflakes", Category.PANTRY],
  ["haferflocken", Category.PANTRY],
  ["pasta", Category.PANTRY],
  ["rice", Category.PANTRY],
  ["flour", Category.PANTRY],
  ["sugar", Category.PANTRY],
  ["oil", Category.PANTRY],
  ["noodles", Category.PANTRY],

  // Household
  ["waschmittel", Category.HOUSEHOLD],
  ["weichspüler", Category.HOUSEHOLD],
  ["spülmittel", Category.HOUSEHOLD],
  ["spülmaschinentabs", Category.HOUSEHOLD],
  ["spülmaschin", Category.HOUSEHOLD],
  ["geschirrspültabs", Category.HOUSEHOLD],
  ["geschirrspül", Category.HOUSEHOLD],
  ["putzmittel", Category.HOUSEHOLD],
  ["reiniger", Category.HOUSEHOLD],
  ["schwamm", Category.HOUSEHOLD],
  ["müllbeutel", Category.HOUSEHOLD],
  ["müllsack", Category.HOUSEHOLD],
  ["alufolie", Category.HOUSEHOLD],
  ["frischhalte", Category.HOUSEHOLD],
  ["backpapier", Category.HOUSEHOLD],
  ["klopapier", Category.HOUSEHOLD],
  ["toilettenpapier", Category.HOUSEHOLD],
  ["küchenrolle", Category.HOUSEHOLD],
  ["zewa", Category.HOUSEHOLD],
  ["taschentuch", Category.HOUSEHOLD],
  ["batterie", Category.HOUSEHOLD],
  ["glühbirne", Category.HOUSEHOLD],
  ["kerze", Category.HOUSEHOLD],
  ["streichholz", Category.HOUSEHOLD],
  ["toilet paper", Category.HOUSEHOLD],
  ["detergent", Category.HOUSEHOLD],
  ["battery", Category.HOUSEHOLD],
  ["batteries", Category.HOUSEHOLD],

  // Personal Care
  ["shampoo", Category.PERSONAL_CARE],
  ["duschgel", Category.PERSONAL_CARE],
  ["seife", Category.PERSONAL_CARE],
  ["zahnpasta", Category.PERSONAL_CARE],
  ["zahnbürste", Category.PERSONAL_CARE],
  ["zahnseide", Category.PERSONAL_CARE],
  ["deo", Category.PERSONAL_CARE],
  ["deodorant", Category.PERSONAL_CARE],
  ["creme", Category.PERSONAL_CARE],
  ["lotion", Category.PERSONAL_CARE],
  ["rasierklinge", Category.PERSONAL_CARE],
  ["rasier", Category.PERSONAL_CARE],
  ["tampon", Category.PERSONAL_CARE],
  ["binde", Category.PERSONAL_CARE],
  ["windel", Category.PERSONAL_CARE],
  ["pflaster", Category.PERSONAL_CARE],
  ["watte", Category.PERSONAL_CARE],
  ["toothpaste", Category.PERSONAL_CARE],
  ["soap", Category.PERSONAL_CARE],
  ["diaper", Category.PERSONAL_CARE],

  // Pet Supplies
  ["hundefutter", Category.PET_SUPPLIES],
  ["katzenfutter", Category.PET_SUPPLIES],
  ["katzenstreu", Category.PET_SUPPLIES],
  ["vogelfutter", Category.PET_SUPPLIES],
  ["tierfutter", Category.PET_SUPPLIES],
  ["leckerli", Category.PET_SUPPLIES],
  ["trockenfutter", Category.PET_SUPPLIES],
  ["nassfutter", Category.PET_SUPPLIES],
  ["dog food", Category.PET_SUPPLIES],
  ["cat food", Category.PET_SUPPLIES],
  ["cat litter", Category.PET_SUPPLIES],
]
