// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEventSeq = `-- name: GetEventSeq :one
SELECT seq FROM events WHERE id = $1
`

// Looks up the seq an event was already assigned by an earlier delivery -
// the fallback InsertEventAtSeq's caller takes on a conflict.
func (q *Queries) GetEventSeq(ctx context.Context, id uuid.UUID) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getEventSeq, id)
	var seq pgtype.Int8
	err := row.Scan(&seq)
	return seq, err
}

const getEventsSince = `-- name: GetEventsSince :many
SELECT id, event_type, aggregate_id, aggregate_type, list_id, payload, occurred_at, client_id, seq
FROM events
WHERE list_id = $1
  AND seq IS NOT NULL
  AND seq > $2
ORDER BY seq ASC
LIMIT $3
`

type GetEventsSinceParams struct {
	ListID     pgtype.UUID `db:"list_id" json:"list_id"`
	SinceSeq   pgtype.Int8 `db:"since_seq" json:"since_seq"`
	LimitCount int32       `db:"limit_count" json:"limit_count"`
}

type GetEventsSinceRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	ListID        pgtype.UUID        `db:"list_id" json:"list_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ClientID      string             `db:"client_id" json:"client_id"`
	Seq           pgtype.Int8        `db:"seq" json:"seq"`
}

// Pull page: every event for one list with seq strictly greater than
// since_seq, oldest-first, capped at limit_count. The controller requests
// limit_count+0 rows and treats a full page as "there may be more" (see
// sync-pull-controller.go) rather than asking for limit+1 here, keeping
// this query's shape identical to what it returns.
func (q *Queries) GetEventsSince(ctx context.Context, arg GetEventsSinceParams) ([]GetEventsSinceRow, error) {
	rows, err := q.db.Query(ctx, getEventsSince, arg.ListID, arg.SinceSeq, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventsSinceRow{}
	for rows.Next() {
		var i GetEventsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.AggregateType,
			&i.ListID,
			&i.Payload,
			&i.OccurredAt,
			&i.ClientID,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKnownEventIdsByList = `-- name: GetKnownEventIdsByList :many
SELECT id
FROM events
WHERE list_id = ANY($1::uuid[])
`

// Which of a set of lists' events this server has durably received - the
// reconcile self-heal endpoint's query. Every row in `events` is now
// durably accepted the moment it exists (see AppendToList/R1), so this is
// simply "does a row exist", with no processed/unprocessed distinction left
// to make. Keyed by list_id rather than aggregate_id: aggregate_id is the
// ingredient id for ingredient.* events, so a single list can span
// arbitrarily many aggregate_ids, but always has exactly one list_id.
func (q *Queries) GetKnownEventIdsByList(ctx context.Context, listIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getKnownEventIdsByList, listIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListHeads = `-- name: GetListHeads :many
SELECT sl.id AS list_id, sl.head_seq AS seq, e.id AS event_id
FROM synced_lists sl
LEFT JOIN events e ON e.list_id = sl.id AND e.seq = sl.head_seq
WHERE sl.id = ANY($1::uuid[])
`

type GetListHeadsRow struct {
	ListID  uuid.UUID   `db:"list_id" json:"list_id"`
	Seq     int64       `db:"seq" json:"seq"`
	EventID pgtype.UUID `db:"event_id" json:"event_id"`
}

// The current pull cursor for every requested list that the registry knows
// about: head_seq plus the id of the event at that seq (NULL when
// head_seq is 0 - a registered-but-empty list, e.g. claimed but not yet
// pushed to). A list the registry has no row for produces no row here at
// all, same omission-based "unknown" signal FindAccessibleListIDs already
// uses elsewhere - see sync-pull-controller.go on why that must stay
// indistinguishable from "not yours".
func (q *Queries) GetListHeads(ctx context.Context, listIds []uuid.UUID) ([]GetListHeadsRow, error) {
	rows, err := q.db.Query(ctx, getListHeads, listIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListHeadsRow{}
	for rows.Next() {
		var i GetListHeadsRow
		if err := rows.Scan(&i.ListID, &i.Seq, &i.EventID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEventAtSeq = `-- name: InsertEventAtSeq :one
INSERT INTO events (id, event_type, aggregate_id, aggregate_type, list_id, payload, occurred_at, client_id, seq, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO NOTHING
RETURNING seq
`

type InsertEventAtSeqParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	ListID        pgtype.UUID        `db:"list_id" json:"list_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ClientID      string             `db:"client_id" json:"client_id"`
	Seq           pgtype.Int8        `db:"seq" json:"seq"`
	UserID        pgtype.Text        `db:"user_id" json:"user_id"`
}

// Assigns the caller-supplied seq directly rather than pulling from a
// global sequence - seq is now a per-list, gap-free counter derived from
// synced_lists.head_seq under that row's lock (see AppendToList), not a
// process-wide invariant (see migration 00009-log-only-server). ON CONFLICT
// DO NOTHING rather than the old no-op-update-for-RETURNING trick: :one
// reports pgx.ErrNoRows on a duplicate delivery, which is exactly the
// signal the caller needs to know it must not consume a fresh seq from its
// running head_seq counter for this event.
func (q *Queries) InsertEventAtSeq(ctx context.Context, arg InsertEventAtSeqParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, insertEventAtSeq,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.AggregateType,
		arg.ListID,
		arg.Payload,
		arg.OccurredAt,
		arg.ClientID,
		arg.Seq,
		arg.UserID,
	)
	var seq pgtype.Int8
	err := row.Scan(&seq)
	return seq, err
}
