// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getKnownEventIds = `-- name: GetKnownEventIds :many
SELECT id
FROM events
WHERE aggregate_id = ANY($1::uuid[])
  AND processed_at IS NOT NULL
`

func (q *Queries) GetKnownEventIds(ctx context.Context, aggregateIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getKnownEventIds, aggregateIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedEvents = `-- name: GetUnprocessedEvents :many
SELECT id, event_type, aggregate_id, aggregate_type, payload, occurred_at, client_id
FROM events
WHERE processed_at IS NULL
ORDER BY received_at ASC
`

type GetUnprocessedEventsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ClientID      string             `db:"client_id" json:"client_id"`
}

func (q *Queries) GetUnprocessedEvents(ctx context.Context) ([]GetUnprocessedEventsRow, error) {
	rows, err := q.db.Query(ctx, getUnprocessedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnprocessedEventsRow{}
	for rows.Next() {
		var i GetUnprocessedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.AggregateType,
			&i.Payload,
			&i.OccurredAt,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (id, event_type, aggregate_id, aggregate_type, payload, occurred_at, client_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET id = events.id
RETURNING processed_at
`

type InsertEventParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ClientID      string             `db:"client_id" json:"client_id"`
}

// Upserts as a no-op update (rather than DO NOTHING) purely so RETURNING
// always yields exactly one row, whether this event_id was just inserted
// or already existed from a previous delivery. Callers use processed_at to
// tell the two cases apart without a second round-trip.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateID,
		arg.AggregateType,
		arg.Payload,
		arg.OccurredAt,
		arg.ClientID,
	)
	var processed_at pgtype.Timestamptz
	err := row.Scan(&processed_at)
	return processed_at, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE events SET processed_at = NOW() WHERE id = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}
