// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list-sharing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addListMember = `-- name: AddListMember :exec
INSERT INTO list_members (list_id, user_id, role, joined_at, invite_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (list_id, user_id) DO NOTHING
`

type AddListMemberParams struct {
	ListID   uuid.UUID          `db:"list_id" json:"list_id"`
	UserID   string             `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	InviteID pgtype.UUID        `db:"invite_id" json:"invite_id"`
}

// Idempotent on (list_id, user_id) so redeeming an invite for a list you're
// already on (including the invite you just claimed ownership with) is a
// safe no-op rather than a primary key violation.
func (q *Queries) AddListMember(ctx context.Context, arg AddListMemberParams) error {
	_, err := q.db.Exec(ctx, addListMember,
		arg.ListID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
		arg.InviteID,
	)
	return err
}

const claimListOwnership = `-- name: ClaimListOwnership :one
INSERT INTO list_members (list_id, user_id, role, joined_at)
SELECT $1, $2, 'owner', $3
WHERE NOT EXISTS (SELECT 1 FROM list_members WHERE list_id = $1)
RETURNING list_id
`

type ClaimListOwnershipParams struct {
	ListID   uuid.UUID          `db:"list_id" json:"list_id"`
	UserID   string             `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

// Adds the caller as owner only if listID has no members yet at all - the
// bootstrap for lists that predate this feature and never had an owner
// recorded anywhere. NOT EXISTS and the INSERT run as one statement so the
// common case doesn't need two round-trips. :one + zero rows (pgx.ErrNoRows)
// means the list already had members and nothing was written.
func (q *Queries) ClaimListOwnership(ctx context.Context, arg ClaimListOwnershipParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimListOwnership, arg.ListID, arg.UserID, arg.JoinedAt)
	var list_id uuid.UUID
	err := row.Scan(&list_id)
	return list_id, err
}

const getActiveListInvites = `-- name: GetActiveListInvites :many
SELECT id, list_id, token_hash, created_by, created_at, expires_at, revoked_at
FROM list_invites
WHERE list_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
ORDER BY created_at DESC
`

type GetActiveListInvitesParams struct {
	ListID uuid.UUID          `db:"list_id" json:"list_id"`
	Now    pgtype.Timestamptz `db:"now" json:"now"`
}

// An invite is active if it hasn't been revoked and hasn't expired as of
// sqlc.arg(now) - the caller passes the current time rather than this query
// using NOW() so results are reproducible in tests.
func (q *Queries) GetActiveListInvites(ctx context.Context, arg GetActiveListInvitesParams) ([]ListInvite, error) {
	rows, err := q.db.Query(ctx, getActiveListInvites, arg.ListID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvite{}
	for rows.Next() {
		var i ListInvite
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListInviteById = `-- name: GetListInviteById :one
SELECT id, list_id, token_hash, created_by, created_at, expires_at, revoked_at
FROM list_invites
WHERE id = $1
`

func (q *Queries) GetListInviteById(ctx context.Context, id uuid.UUID) (ListInvite, error) {
	row := q.db.QueryRow(ctx, getListInviteById, id)
	var i ListInvite
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getListInviteByTokenHash = `-- name: GetListInviteByTokenHash :one
SELECT id, list_id, token_hash, created_by, created_at, expires_at, revoked_at
FROM list_invites
WHERE token_hash = $1
`

func (q *Queries) GetListInviteByTokenHash(ctx context.Context, tokenHash string) (ListInvite, error) {
	row := q.db.QueryRow(ctx, getListInviteByTokenHash, tokenHash)
	var i ListInvite
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getListMember = `-- name: GetListMember :one
SELECT list_id, user_id, role, joined_at, invite_id
FROM list_members
WHERE list_id = $1 AND user_id = $2
`

type GetListMemberParams struct {
	ListID uuid.UUID `db:"list_id" json:"list_id"`
	UserID string    `db:"user_id" json:"user_id"`
}

func (q *Queries) GetListMember(ctx context.Context, arg GetListMemberParams) (ListMember, error) {
	row := q.db.QueryRow(ctx, getListMember, arg.ListID, arg.UserID)
	var i ListMember
	err := row.Scan(
		&i.ListID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.InviteID,
	)
	return i, err
}

const insertListInvite = `-- name: InsertListInvite :exec
INSERT INTO list_invites (id, list_id, token_hash, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertListInviteParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ListID    uuid.UUID          `db:"list_id" json:"list_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertListInvite(ctx context.Context, arg InsertListInviteParams) error {
	_, err := q.db.Exec(ctx, insertListInvite,
		arg.ID,
		arg.ListID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const revokeListInvite = `-- name: RevokeListInvite :exec
UPDATE list_invites
SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeListInviteParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ID        uuid.UUID          `db:"id" json:"id"`
}

// The `revoked_at IS NULL` guard makes revoking an already-revoked invite a
// true no-op (zero rows affected) rather than overwriting the original
// revocation time - ListSharingService treats both as success either way,
// but this keeps the first revocation timestamp authoritative.
func (q *Queries) RevokeListInvite(ctx context.Context, arg RevokeListInviteParams) error {
	_, err := q.db.Exec(ctx, revokeListInvite, arg.RevokedAt, arg.ID)
	return err
}
