// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list-sharing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addListMember = `-- name: AddListMember :exec
INSERT INTO list_members (list_id, user_id, role, joined_at, invite_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (list_id, user_id) DO NOTHING
`

type AddListMemberParams struct {
	ListID   uuid.UUID          `db:"list_id" json:"list_id"`
	UserID   string             `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	InviteID pgtype.UUID        `db:"invite_id" json:"invite_id"`
}

// Idempotent on (list_id, user_id) so redeeming an invite for a list you're
// already on (including the invite you just claimed ownership with) is a
// safe no-op rather than a primary key violation.
func (q *Queries) AddListMember(ctx context.Context, arg AddListMemberParams) error {
	_, err := q.db.Exec(ctx, addListMember,
		arg.ListID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
		arg.InviteID,
	)
	return err
}

const claimListOwnership = `-- name: ClaimListOwnership :one
WITH registered AS (
    INSERT INTO synced_lists (id, created_at)
    VALUES ($1, $3)
    ON CONFLICT (id) DO NOTHING
)
INSERT INTO list_members (list_id, user_id, role, joined_at)
SELECT $1, $2, 'owner', $3
WHERE NOT EXISTS (SELECT 1 FROM list_members WHERE list_id = $1)
RETURNING list_id
`

type ClaimListOwnershipParams struct {
	ListID   uuid.UUID          `db:"list_id" json:"list_id"`
	UserID   string             `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

// Adds the caller as owner only if listID has no members yet at all, and
// registers the list in the same statement. :one + zero rows
// (pgx.ErrNoRows) means the list already had members and no membership was
// written.
//
// The registry insert is a data-modifying CTE rather than a second
// round-trip so the two can't diverge: Postgres runs it exactly once and to
// completion, and list_members' foreign key is checked after the whole
// statement, by which point the parent row exists. A member row without a
// registry row is therefore not representable - which is what makes the
// foreign key added in 00008 truthful rather than aspirational.
func (q *Queries) ClaimListOwnership(ctx context.Context, arg ClaimListOwnershipParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimListOwnership, arg.ListID, arg.UserID, arg.JoinedAt)
	var list_id uuid.UUID
	err := row.Scan(&list_id)
	return list_id, err
}

const countListMembers = `-- name: CountListMembers :one
SELECT COUNT(*) FROM list_members WHERE list_id = $1
`

func (q *Queries) CountListMembers(ctx context.Context, listID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countListMembers, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccessibleListIDs = `-- name: GetAccessibleListIDs :many
SELECT list_id
FROM list_members
WHERE list_id = ANY($1::uuid[]) AND user_id = $2
`

type GetAccessibleListIDsParams struct {
	ListIds []uuid.UUID `db:"list_ids" json:"list_ids"`
	UserID  string      `db:"user_id" json:"user_id"`
}

// Which of the given list ids the caller is a member (owner or member) of -
// the filter behind every read path (ListAccessService.FilterAccessible).
// Deliberately returns a subset rather than erroring on a list the caller
// has no access to: a batch read (e.g. /sync/head) must not turn into an
// enumeration oracle that tells a caller "that id exists but isn't yours"
// vs. "that id doesn't exist" - both simply come back missing.
func (q *Queries) GetAccessibleListIDs(ctx context.Context, arg GetAccessibleListIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAccessibleListIDs, arg.ListIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var list_id uuid.UUID
		if err := rows.Scan(&list_id); err != nil {
			return nil, err
		}
		items = append(items, list_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveListInvites = `-- name: GetActiveListInvites :many
SELECT id, list_id, token_hash, created_by, created_at, expires_at, revoked_at, list_name, created_by_name, created_by_picture_url
FROM list_invites
WHERE list_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
ORDER BY created_at DESC
`

type GetActiveListInvitesParams struct {
	ListID uuid.UUID          `db:"list_id" json:"list_id"`
	Now    pgtype.Timestamptz `db:"now" json:"now"`
}

// An invite is active if it hasn't been revoked and hasn't expired as of
// sqlc.arg(now) - the caller passes the current time rather than this query
// using NOW() so results are reproducible in tests.
func (q *Queries) GetActiveListInvites(ctx context.Context, arg GetActiveListInvitesParams) ([]ListInvite, error) {
	rows, err := q.db.Query(ctx, getActiveListInvites, arg.ListID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvite{}
	for rows.Next() {
		var i ListInvite
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ListName,
			&i.CreatedByName,
			&i.CreatedByPictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimedListIDs = `-- name: GetClaimedListIDs :many
SELECT DISTINCT list_id
FROM list_members
WHERE list_id = ANY($1::uuid[])
`

// Which of the given list ids already have at least one member, regardless
// of who - the pre-check behind ListAccessService.AuthorizeWrite's claim
// phase. Distinguishes "nobody has pushed to this list yet" (eligible for
// ClaimOwnershipIfUnowned) from "someone else already owns it" (must be
// rejected) without granting access or claiming anything itself.
func (q *Queries) GetClaimedListIDs(ctx context.Context, listIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getClaimedListIDs, listIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var list_id uuid.UUID
		if err := rows.Scan(&list_id); err != nil {
			return nil, err
		}
		items = append(items, list_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListInviteById = `-- name: GetListInviteById :one
SELECT id, list_id, token_hash, created_by, created_at, expires_at, revoked_at, list_name, created_by_name, created_by_picture_url
FROM list_invites
WHERE id = $1
`

func (q *Queries) GetListInviteById(ctx context.Context, id uuid.UUID) (ListInvite, error) {
	row := q.db.QueryRow(ctx, getListInviteById, id)
	var i ListInvite
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ListName,
		&i.CreatedByName,
		&i.CreatedByPictureUrl,
	)
	return i, err
}

const getListInviteByTokenHash = `-- name: GetListInviteByTokenHash :one
SELECT id, list_id, token_hash, created_by, created_at, expires_at, revoked_at, list_name, created_by_name, created_by_picture_url
FROM list_invites
WHERE token_hash = $1
`

func (q *Queries) GetListInviteByTokenHash(ctx context.Context, tokenHash string) (ListInvite, error) {
	row := q.db.QueryRow(ctx, getListInviteByTokenHash, tokenHash)
	var i ListInvite
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ListName,
		&i.CreatedByName,
		&i.CreatedByPictureUrl,
	)
	return i, err
}

const getListMember = `-- name: GetListMember :one
SELECT list_id, user_id, role, joined_at, invite_id
FROM list_members
WHERE list_id = $1 AND user_id = $2
`

type GetListMemberParams struct {
	ListID uuid.UUID `db:"list_id" json:"list_id"`
	UserID string    `db:"user_id" json:"user_id"`
}

func (q *Queries) GetListMember(ctx context.Context, arg GetListMemberParams) (ListMember, error) {
	row := q.db.QueryRow(ctx, getListMember, arg.ListID, arg.UserID)
	var i ListMember
	err := row.Scan(
		&i.ListID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.InviteID,
	)
	return i, err
}

const getListsForUser = `-- name: GetListsForUser :many
SELECT list_id, user_id, role, joined_at, invite_id
FROM list_members
WHERE user_id = $1
ORDER BY joined_at
`

// Every list the caller owns or is a member of - the discovery endpoint
// behind "restore my lists after reinstall" (sync-sharing-target.md §7.1/§8).
// Self-scoped by the caller's own verified user_id, so unlike
// GetAccessibleListIDs this needs no candidate list_ids and raises no
// enumeration concern.
func (q *Queries) GetListsForUser(ctx context.Context, userID string) ([]ListMember, error) {
	rows, err := q.db.Query(ctx, getListsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMember{}
	for rows.Next() {
		var i ListMember
		if err := rows.Scan(
			&i.ListID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.InviteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertListInvite = `-- name: InsertListInvite :exec
INSERT INTO list_invites (id, list_id, token_hash, created_by, created_at, expires_at, list_name, created_by_name, created_by_picture_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertListInviteParams struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	ListID              uuid.UUID          `db:"list_id" json:"list_id"`
	TokenHash           string             `db:"token_hash" json:"token_hash"`
	CreatedBy           string             `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ListName            string             `db:"list_name" json:"list_name"`
	CreatedByName       pgtype.Text        `db:"created_by_name" json:"created_by_name"`
	CreatedByPictureUrl pgtype.Text        `db:"created_by_picture_url" json:"created_by_picture_url"`
}

func (q *Queries) InsertListInvite(ctx context.Context, arg InsertListInviteParams) error {
	_, err := q.db.Exec(ctx, insertListInvite,
		arg.ID,
		arg.ListID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ListName,
		arg.CreatedByName,
		arg.CreatedByPictureUrl,
	)
	return err
}

const lockOrCreateSyncedList = `-- name: LockOrCreateSyncedList :one
INSERT INTO synced_lists (id, head_seq, created_at)
VALUES ($1, 0, $2)
ON CONFLICT (id) DO UPDATE SET id = synced_lists.id
RETURNING head_seq
`

type LockOrCreateSyncedListParams struct {
	ListID    uuid.UUID          `db:"list_id" json:"list_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Row-locks the list's registry entry for the duration of the caller's
// transaction, serializing seq assignment against any concurrent append for
// the same list - this is what makes seq assignment safe across multiple
// API replicas instead of depending on "exactly one EventIngestor goroutine
// in one process" (see 6.4 in frontend/docs/sync-sharing-target.md).
// Upserts as a no-op update so RETURNING always yields the current
// head_seq, whether the row already existed (the common case -
// ClaimListOwnership already created it) or this is a defensive first
// write reaching AppendToList without a prior claim.
func (q *Queries) LockOrCreateSyncedList(ctx context.Context, arg LockOrCreateSyncedListParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockOrCreateSyncedList, arg.ListID, arg.CreatedAt)
	var head_seq int64
	err := row.Scan(&head_seq)
	return head_seq, err
}

const revokeListInvite = `-- name: RevokeListInvite :exec
UPDATE list_invites
SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeListInviteParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ID        uuid.UUID          `db:"id" json:"id"`
}

// The `revoked_at IS NULL` guard makes revoking an already-revoked invite a
// true no-op (zero rows affected) rather than overwriting the original
// revocation time - ListSharingService treats both as success either way,
// but this keeps the first revocation timestamp authoritative.
func (q *Queries) RevokeListInvite(ctx context.Context, arg RevokeListInviteParams) error {
	_, err := q.db.Exec(ctx, revokeListInvite, arg.RevokedAt, arg.ID)
	return err
}

const syncedListExists = `-- name: SyncedListExists :one
SELECT EXISTS (SELECT 1 FROM synced_lists WHERE id = $1)
`

// "Does the server hold a log for this list" - the registry replacement for
// the old todo_lists existence check. Deliberately returns no content: the
// server has none to return.
func (q *Queries) SyncedListExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, syncedListExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSyncedListHeadSeq = `-- name: UpdateSyncedListHeadSeq :exec
UPDATE synced_lists SET head_seq = $1 WHERE id = $2
`

type UpdateSyncedListHeadSeqParams struct {
	HeadSeq int64     `db:"head_seq" json:"head_seq"`
	ListID  uuid.UUID `db:"list_id" json:"list_id"`
}

func (q *Queries) UpdateSyncedListHeadSeq(ctx context.Context, arg UpdateSyncedListHeadSeqParams) error {
	_, err := q.db.Exec(ctx, updateSyncedListHeadSeq, arg.HeadSeq, arg.ListID)
	return err
}
