// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ReceivedAt    pgtype.Timestamptz `db:"received_at" json:"received_at"`
	ClientID      string             `db:"client_id" json:"client_id"`
	ListID        pgtype.UUID        `db:"list_id" json:"list_id"`
	Seq           pgtype.Int8        `db:"seq" json:"seq"`
	UserID        pgtype.Text        `db:"user_id" json:"user_id"`
}

type ListInvite struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	ListID              uuid.UUID          `db:"list_id" json:"list_id"`
	TokenHash           string             `db:"token_hash" json:"token_hash"`
	CreatedBy           string             `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	ListName            string             `db:"list_name" json:"list_name"`
	CreatedByName       pgtype.Text        `db:"created_by_name" json:"created_by_name"`
	CreatedByPictureUrl pgtype.Text        `db:"created_by_picture_url" json:"created_by_picture_url"`
}

type ListMember struct {
	ListID   uuid.UUID          `db:"list_id" json:"list_id"`
	UserID   string             `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	InviteID pgtype.UUID        `db:"invite_id" json:"invite_id"`
}

type SyncedList struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	HeadSeq   int64              `db:"head_seq" json:"head_seq"`
}
