// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ReceivedAt    pgtype.Timestamptz `db:"received_at" json:"received_at"`
	ClientID      string             `db:"client_id" json:"client_id"`
	ProcessedAt   pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	ListID        pgtype.UUID        `db:"list_id" json:"list_id"`
	Seq           pgtype.Int8        `db:"seq" json:"seq"`
}

type Todo struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	IsCompleted bool               `db:"is_completed" json:"is_completed"`
	TodoListID  uuid.UUID          `db:"todo_list_id" json:"todo_list_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type TodoList struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
