// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Idempotent on (list_id, user_id) so redeeming an invite for a list you're
	// already on (including the invite you just claimed ownership with) is a
	// safe no-op rather than a primary key violation.
	AddListMember(ctx context.Context, arg AddListMemberParams) error
	// Adds the caller as owner only if listID has no members yet at all, and
	// registers the list in the same statement. :one + zero rows
	// (pgx.ErrNoRows) means the list already had members and no membership was
	// written.
	//
	// The registry insert is a data-modifying CTE rather than a second
	// round-trip so the two can't diverge: Postgres runs it exactly once and to
	// completion, and list_members' foreign key is checked after the whole
	// statement, by which point the parent row exists. A member row without a
	// registry row is therefore not representable - which is what makes the
	// foreign key added in 00008 truthful rather than aspirational.
	ClaimListOwnership(ctx context.Context, arg ClaimListOwnershipParams) (uuid.UUID, error)
	// Which of the given list ids the caller is a member (owner or member) of -
	// the filter behind every read path (ListAccessService.FilterAccessible).
	// Deliberately returns a subset rather than erroring on a list the caller
	// has no access to: a batch read (e.g. /sync/head) must not turn into an
	// enumeration oracle that tells a caller "that id exists but isn't yours"
	// vs. "that id doesn't exist" - both simply come back missing.
	GetAccessibleListIDs(ctx context.Context, arg GetAccessibleListIDsParams) ([]uuid.UUID, error)
	// An invite is active if it hasn't been revoked and hasn't expired as of
	// sqlc.arg(now) - the caller passes the current time rather than this query
	// using NOW() so results are reproducible in tests.
	GetActiveListInvites(ctx context.Context, arg GetActiveListInvitesParams) ([]ListInvite, error)
	// Which of the given list ids already have at least one member, regardless
	// of who - the pre-check behind ListAccessService.AuthorizeWrite's claim
	// phase. Distinguishes "nobody has pushed to this list yet" (eligible for
	// ClaimOwnershipIfUnowned) from "someone else already owns it" (must be
	// rejected) without granting access or claiming anything itself.
	GetClaimedListIDs(ctx context.Context, listIds []uuid.UUID) ([]uuid.UUID, error)
	// Looks up the seq an event was already assigned by an earlier delivery -
	// the fallback InsertEventAtSeq's caller takes on a conflict.
	GetEventSeq(ctx context.Context, id uuid.UUID) (pgtype.Int8, error)
	// Pull page: every event for one list with seq strictly greater than
	// since_seq, oldest-first, capped at limit_count. The controller requests
	// limit_count+0 rows and treats a full page as "there may be more" (see
	// sync-pull-controller.go) rather than asking for limit+1 here, keeping
	// this query's shape identical to what it returns.
	GetEventsSince(ctx context.Context, arg GetEventsSinceParams) ([]GetEventsSinceRow, error)
	// Which of a set of lists' events this server has durably received - the
	// reconcile self-heal endpoint's query. Every row in `events` is now
	// durably accepted the moment it exists (see AppendToList/R1), so this is
	// simply "does a row exist", with no processed/unprocessed distinction left
	// to make. Keyed by list_id rather than aggregate_id: aggregate_id is the
	// ingredient id for ingredient.* events, so a single list can span
	// arbitrarily many aggregate_ids, but always has exactly one list_id.
	GetKnownEventIdsByList(ctx context.Context, listIds []uuid.UUID) ([]uuid.UUID, error)
	// The current pull cursor for every requested list that the registry knows
	// about: head_seq plus the id of the event at that seq (NULL when
	// head_seq is 0 - a registered-but-empty list, e.g. claimed but not yet
	// pushed to). A list the registry has no row for produces no row here at
	// all, same omission-based "unknown" signal FindAccessibleListIDs already
	// uses elsewhere - see sync-pull-controller.go on why that must stay
	// indistinguishable from "not yours".
	GetListHeads(ctx context.Context, listIds []uuid.UUID) ([]GetListHeadsRow, error)
	GetListInviteById(ctx context.Context, id uuid.UUID) (ListInvite, error)
	GetListInviteByTokenHash(ctx context.Context, tokenHash string) (ListInvite, error)
	GetListMember(ctx context.Context, arg GetListMemberParams) (ListMember, error)
	// Assigns the caller-supplied seq directly rather than pulling from a
	// global sequence - seq is now a per-list, gap-free counter derived from
	// synced_lists.head_seq under that row's lock (see AppendToList), not a
	// process-wide invariant (see migration 00009-log-only-server). ON CONFLICT
	// DO NOTHING rather than the old no-op-update-for-RETURNING trick: :one
	// reports pgx.ErrNoRows on a duplicate delivery, which is exactly the
	// signal the caller needs to know it must not consume a fresh seq from its
	// running head_seq counter for this event.
	InsertEventAtSeq(ctx context.Context, arg InsertEventAtSeqParams) (pgtype.Int8, error)
	InsertListInvite(ctx context.Context, arg InsertListInviteParams) error
	// Row-locks the list's registry entry for the duration of the caller's
	// transaction, serializing seq assignment against any concurrent append for
	// the same list - this is what makes seq assignment safe across multiple
	// API replicas instead of depending on "exactly one EventIngestor goroutine
	// in one process" (see frontend/docs/sync-server-registry-roadmap.md).
	// Upserts as a no-op update so RETURNING always yields the current
	// head_seq, whether the row already existed (the common case -
	// ClaimListOwnership already created it) or this is a defensive first
	// write reaching AppendToList without a prior claim.
	LockOrCreateSyncedList(ctx context.Context, arg LockOrCreateSyncedListParams) (int64, error)
	// The `revoked_at IS NULL` guard makes revoking an already-revoked invite a
	// true no-op (zero rows affected) rather than overwriting the original
	// revocation time - ListSharingService treats both as success either way,
	// but this keeps the first revocation timestamp authoritative.
	RevokeListInvite(ctx context.Context, arg RevokeListInviteParams) error
	// "Does the server hold a log for this list" - the registry replacement for
	// the old todo_lists existence check. Deliberately returns no content: the
	// server has none to return.
	SyncedListExists(ctx context.Context, id uuid.UUID) (bool, error)
	UpdateSyncedListHeadSeq(ctx context.Context, arg UpdateSyncedListHeadSeqParams) error
}

var _ Querier = (*Queries)(nil)
