// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateToDo(ctx context.Context, arg CreateToDoParams) (Todo, error)
	CreateToDoList(ctx context.Context, arg CreateToDoListParams) (TodoList, error)
	DeleteToDo(ctx context.Context, id uuid.UUID) error
	DeleteToDoList(ctx context.Context, id uuid.UUID) error
	GetAllToDoLists(ctx context.Context) ([]GetAllToDoListsRow, error)
	GetAllToDos(ctx context.Context) ([]GetAllToDosRow, error)
	GetKnownEventIds(ctx context.Context, aggregateIds []uuid.UUID) ([]uuid.UUID, error)
	GetToDoById(ctx context.Context, id uuid.UUID) (GetToDoByIdRow, error)
	GetToDoListById(ctx context.Context, id uuid.UUID) (GetToDoListByIdRow, error)
	GetUnprocessedEvents(ctx context.Context) ([]GetUnprocessedEventsRow, error)
	// Upserts as a no-op update (rather than DO NOTHING) purely so RETURNING
	// always yields exactly one row, whether this event_id was just inserted
	// or already existed from a previous delivery. Callers use processed_at to
	// tell the two cases apart without a second round-trip.
	InsertEvent(ctx context.Context, arg InsertEventParams) (pgtype.Timestamptz, error)
	MarkEventProcessed(ctx context.Context, id uuid.UUID) error
	UpdateToDo(ctx context.Context, arg UpdateToDoParams) error
	UpdateToDoList(ctx context.Context, arg UpdateToDoListParams) error
}

var _ Querier = (*Queries)(nil)
