// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo-lists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createToDoList = `-- name: CreateToDoList :one
INSERT INTO todo_lists (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, updated_at, deleted_at
`

type CreateToDoListParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateToDoList(ctx context.Context, arg CreateToDoListParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, createToDoList,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteToDoList = `-- name: DeleteToDoList :exec
UPDATE todo_lists SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteToDoList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteToDoList, id)
	return err
}

const getAllToDoLists = `-- name: GetAllToDoLists :many
SELECT p.id, p.name, p.created_at, p.updated_at
FROM todo_lists p
WHERE p.deleted_at IS NULL
ORDER BY p.created_at DESC
`

type GetAllToDoListsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAllToDoLists(ctx context.Context) ([]GetAllToDoListsRow, error) {
	rows, err := q.db.Query(ctx, getAllToDoLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllToDoListsRow{}
	for rows.Next() {
		var i GetAllToDoListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToDoListById = `-- name: GetToDoListById :one
SELECT p.id, p.name, p.created_at, p.updated_at
FROM todo_lists p
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetToDoListByIdRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetToDoListById(ctx context.Context, id uuid.UUID) (GetToDoListByIdRow, error) {
	row := q.db.QueryRow(ctx, getToDoListById, id)
	var i GetToDoListByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToDoList = `-- name: UpdateToDoList :exec
UPDATE todo_lists 
SET name = $2, updated_at = $3
WHERE id = $1
`

type UpdateToDoListParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateToDoList(ctx context.Context, arg UpdateToDoListParams) error {
	_, err := q.db.Exec(ctx, updateToDoList, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}
