// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createToDo = `-- name: CreateToDo :one
INSERT INTO todos (id, name, is_completed, todo_list_id, created_at, updated_at, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, is_completed, todo_list_id, created_at, updated_at, completed_at, deleted_at
`

type CreateToDoParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	IsCompleted bool               `db:"is_completed" json:"is_completed"`
	TodoListID  uuid.UUID          `db:"todo_list_id" json:"todo_list_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) CreateToDo(ctx context.Context, arg CreateToDoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createToDo,
		arg.ID,
		arg.Name,
		arg.IsCompleted,
		arg.TodoListID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsCompleted,
		&i.TodoListID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteToDo = `-- name: DeleteToDo :exec
UPDATE todos SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteToDo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteToDo, id)
	return err
}

const getAllToDos = `-- name: GetAllToDos :many
SELECT p.id, p.name, p.is_completed, p.todo_list_id, p.created_at, p.updated_at, p.completed_at
FROM todos p
WHERE p.deleted_at IS NULL
ORDER BY p.created_at DESC
`

type GetAllToDosRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	IsCompleted bool               `db:"is_completed" json:"is_completed"`
	TodoListID  uuid.UUID          `db:"todo_list_id" json:"todo_list_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) GetAllToDos(ctx context.Context) ([]GetAllToDosRow, error) {
	rows, err := q.db.Query(ctx, getAllToDos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllToDosRow{}
	for rows.Next() {
		var i GetAllToDosRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsCompleted,
			&i.TodoListID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getToDoById = `-- name: GetToDoById :one
SELECT p.id, p.name, p.is_completed, p.todo_list_id, p.created_at, p.updated_at, p.completed_at
FROM todos p
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetToDoByIdRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	IsCompleted bool               `db:"is_completed" json:"is_completed"`
	TodoListID  uuid.UUID          `db:"todo_list_id" json:"todo_list_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) GetToDoById(ctx context.Context, id uuid.UUID) (GetToDoByIdRow, error) {
	row := q.db.QueryRow(ctx, getToDoById, id)
	var i GetToDoByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsCompleted,
		&i.TodoListID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateToDo = `-- name: UpdateToDo :exec
UPDATE todos 
SET name = $2, is_completed = $3, todo_list_id = $4, updated_at = $5, completed_at = $6
WHERE id = $1
`

type UpdateToDoParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	IsCompleted bool               `db:"is_completed" json:"is_completed"`
	TodoListID  uuid.UUID          `db:"todo_list_id" json:"todo_list_id"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) UpdateToDo(ctx context.Context, arg UpdateToDoParams) error {
	_, err := q.db.Exec(ctx, updateToDo,
		arg.ID,
		arg.Name,
		arg.IsCompleted,
		arg.TodoListID,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}
