// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user-profiles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getListMemberProfiles = `-- name: GetListMemberProfiles :many
SELECT m.user_id, COALESCE(p.first_name, '')::text AS first_name
FROM list_members m LEFT JOIN user_profiles p ON p.user_id = m.user_id
WHERE m.list_id = $1 ORDER BY m.user_id
`

type GetListMemberProfilesRow struct {
	UserID    string `db:"user_id" json:"user_id"`
	FirstName string `db:"first_name" json:"first_name"`
}

func (q *Queries) GetListMemberProfiles(ctx context.Context, listID uuid.UUID) ([]GetListMemberProfilesRow, error) {
	rows, err := q.db.Query(ctx, getListMemberProfiles, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetListMemberProfilesRow{}
	for rows.Next() {
		var i GetListMemberProfilesRow
		if err := rows.Scan(&i.UserID, &i.FirstName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec
INSERT INTO user_profiles (user_id, first_name) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET first_name = EXCLUDED.first_name
WHERE user_profiles.first_name IS DISTINCT FROM EXCLUDED.first_name
`

type UpsertUserProfileParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	FirstName string `db:"first_name" json:"first_name"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfile, arg.UserID, arg.FirstName)
	return err
}
