{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.existingSecretKeys.databaseUrl }}: {{ .Values.secret.databaseUrl | quote }}
  {{ .Values.secret.existingSecretKeys.keycloakIssuer }}: {{ .Values.secret.keycloakIssuer | quote }}
  {{ .Values.secret.existingSecretKeys.keycloakClientId }}: {{ .Values.secret.keycloakClientId | quote }}
{{- end }}
