{{- if and .Values.backend.enabled (not .Values.backend.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imp-list.componentFullname" (dict "root" $ "component" "backend") }}
  labels:
    {{- include "imp-list.labels" (dict "root" $ "component" "backend" "version" .Values.backend.image.tag) | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backend.secret.existingSecretKeys.databaseUrl }}: {{ .Values.backend.secret.databaseUrl | quote }}
{{- end }}
