name: Lint Go (gofmt, go vet)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint Go (gofmt, go vet)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: 🐹 Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: 🏃‍♂️ Check formatting (gofmt)
        run: test -z "$(gofmt -l .)"
        working-directory: ./backend

      - name: 🏃‍♂️ Run go vet
        run: go vet ./...
        working-directory: ./backend
