name: Backend Test (go)

on:
  push:
    branches: [main, master]
    paths:
      - "backend/**"
  pull_request:
    branches: [main, master]
    paths:
      - "backend/**"

jobs:
  test:
    name: Backend Test (go)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: 🐹 Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: 🏃‍♂️ Run Tests
        run: go test ./...
        working-directory: ./backend
