name: Tests (jest)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Tests (jest)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: 📦 Setup Node and dependencies
        uses: ./.github/actions/setup-node-install

      - name: 🏃‍♂️ Run Tests
        run: pnpm run test:ci
        working-directory: ./frontend

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@fb83bcbaeb5ca467936175796f862a2992938833 # main
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          coverage-summary-path: ./frontend/coverage/coverage-summary.json
          summary-title: "💯 Test Coverage"
          badge-title: Coverage
          create-new-comment: false
          junitxml-title: 😎 Tests Results
          junitxml-path: ./frontend/coverage/jest-junit.xml
          coverage-title: 👀 Tests Details
          coverage-path: ./frontend/coverage/coverage.txt
          report-only-changed-files: true
